# Name of loaded config, to show to user
name = "USB Mass Storage BDM driver"

# Drivers this driver depends on (config file must exist)
depends = "bdm"

# Modules to load
[[module]]
file = "usbd_mini.irx"
# Modules that emulate the sceCdRead function must operate at a higher
# priority than the highest possible game priority.
#
# If the priority is lower (higher number) then some games will wait in
# and endless loop for data, but the waiting thread will then cause the
# data to never be processed.
#
# This causes some games to 'need' MODE2 (sync reads) to work.
#
# Supported parameters:
# - dev   = maxDevices
# - ed    = maxEndpoints
# - gtd   = maxTransfDesc
# - itd   = maxIsoTransfDesc
# - ioreq = maxIoReqs
# - conf  = maxStaticDescSize
# - hub   = maxHubDevices
# - port  = maxPortsPerHub
# - thpri = hcdThreadPrio,cbThreadPrio
args = ["dev=16", "ed=32", "gtd=64", "itd=64", "hub=4", "port=4", "thpri=7,8"]
# Save 13KiB IOP RAM
#args = ["dev=4", "ed=8", "gtd=16", "itd=16", "hub=2", "port=4", "thpri=7,8"]
[[module]]
file = "usbmass_bd_mini.irx"

# Modules of the game that are faked/blocked
[[fake]]
file = "USBD.IRX"
name = "USB_driver"
version = 0x0204
startrv = 2 # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
