# Name of loaded config, to show to user
name = "HDLoader filesystem driver"

# Drivers this driver depends on (config file must exist)
#depends = ["i_bdm"]

# Modules to load in load environment
[[module]]
file = "ps2hdd-bdm.irx"
args = ["-o", "4", "-n", "20"]
env = ["LE"]
[[module]]
file = "hdlfs.irx"
env = ["LE"]
